/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthenticatedUploadsRouteImport } from './routes/_authenticated/uploads'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat.stream'
import { Route as AuthenticatedChatSessionIdRouteImport } from './routes/_authenticated/chat.$sessionId'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadsRoute = AuthenticatedUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat/stream',
  path: '/api/chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatSessionIdRoute =
  AuthenticatedChatSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/uploads': typeof AuthenticatedUploadsRoute
  '/share/$token': typeof ShareTokenRoute
  '/chat/$sessionId': typeof AuthenticatedChatSessionIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/uploads': typeof AuthenticatedUploadsRoute
  '/share/$token': typeof ShareTokenRoute
  '/chat/$sessionId': typeof AuthenticatedChatSessionIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/chat': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/uploads': typeof AuthenticatedUploadsRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/chat/$sessionId': typeof AuthenticatedChatSessionIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/chat'
    | '/settings'
    | '/uploads'
    | '/share/$token'
    | '/chat/$sessionId'
    | '/api/chat/stream'
    | '/api/public/stripe-webhook'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/uploads'
    | '/share/$token'
    | '/chat/$sessionId'
    | '/api/chat/stream'
    | '/api/public/stripe-webhook'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/_authenticated/chat'
    | '/_authenticated/settings'
    | '/_authenticated/uploads'
    | '/share/$token'
    | '/_authenticated/chat/$sessionId'
    | '/api/chat/stream'
    | '/api/public/stripe-webhook'
    | '/_authenticated/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/uploads': {
      id: '/_authenticated/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof AuthenticatedUploadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/stream': {
      id: '/api/chat/stream'
      path: '/api/chat/stream'
      fullPath: '/api/chat/stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$sessionId': {
      id: '/_authenticated/chat/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof AuthenticatedChatSessionIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatSessionIdRoute: typeof AuthenticatedChatSessionIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatSessionIdRoute: AuthenticatedChatSessionIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUploadsRoute: typeof AuthenticatedUploadsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUploadsRoute: AuthenticatedUploadsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
